### ISSUE TITLE
findWidgetById

### ISSUE THREAD

**Issue by citmusa** [twotoasters/RecyclerViewLib#10]
In android studio,  by doing the basic example

all this is in the build.gradle
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:support-v13:20.0.0'
    compile 'com.android.support:support-v4:20.0.0'
    compile 'com.android.support:appcompat-v7:20.0.0'
    compile 'com.android.support:gridlayout-v7:19.1.0'
    compile 'com.android.support:mediarouter-v7:19.1.0'
    provided 'com.twotoasters.RecyclerViewLib:library:1.0.0'
    compile 'com.google.android.gms:play-services:5.2.08'
}

in the activity, import com.twotoasters.android.support.v7.widget.RecyclerView;
was correctly added

But in onCreate method 
  mRecyclerView = findWidgetById(R.id.recyclerview);
I got this =(
cannot resolve method findWidgetById

**Comment by MinceMan** [comment]
`findWidgetById` is a method defined in the sample activity. Why this method is neat is because you don't have to cast when using it unlike `findVeiwById`. Just add the following code to your activity if you want to use it. 

```
public <T extends View> T findWidgetById(int resId) {
    return (T) findViewById(resId);
}
```
