### ISSUE TITLE
Great work but i've a small problem.

### ISSUE THREAD

**Issue by Ks89** [twotoasters/RecyclerViewLib#11]
Hi, great work, really!

But, i want to use only the classes PendingItemAnimator and GarageItemAnimator for a personal project.
For example, If i want to use this with "setItemAnimator(new GarageDoorItemAnimator());" i've conflict between your RecyclerView and the original RecyclerView inside the Appcompat v7.
Ok, this is not a big problem, but for me that i don't want to use all your customization it's boring.
Now i imported in my project the two classes for animations. I changed the import to restore the original appcompat v7, and GarageDoorItemAnimator is working perfectly.

It's possible to create a library only with this animations? Or use the original appcompatv7 to solve this problems?

I know, i know, i can use directly your RecyclerView, but i want to use only a small part of this library and i want to maintain the original recycler view.

**Comment by MinceMan** [comment]
Sorry for the slow reply. I don't want to create a repo just for this so I created a [gist](https://gist.github.com/MinceMan/e968be8577b6d069da43) for the PendingItemAnimator updated to work with the final version of RecyclerView.
